import React from "react";
import "./globals.css";
import CustomLayout from "../components/CustomLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <CustomLayout>{children}</CustomLayout>
      </body>
    </html>
  );
}
